---
 - name: install docker
   hosts: loadbalancer
   become: yes

   tasks:
     - name: update the repository and install pre-reqs
       apt: name={{item}} state=present update_cache=yes
       loop:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - software-properties-common

    tasks:
      - name: add gpg key
        command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
